export const ADD_TODO_PENDING = 'ADD_TODOS_PENDING'
export const ADD_TODO_FULFILLED = 'ADD_TODOS_FULFILLED'
export const ADD_TODO_REJECTED = 'ADD_TODOS_REJECTED'

export const FETCH_TODO_PENDING = 'FETCH_TODOS_PENDING'
export const FETCH_TODO_FULFILLED = 'FETCH_TODOS_FULFILLED'
export const FETCH_TODO_REJECTED = 'FETCH_TODOSS_REJECTED'

export const EDIT_TODO_PENDING = 'EDIT_TODOS_PENDING'
export const EDIT_TODO_FULFILLED = 'EDIT_TODOS_FULFILLED'
export const EDIT_TODO_REJECTED = 'EDIT_TODOS_REJECTED'

export const DELETE_TODO_PENDING = 'DELETE_TODOS_PENDING'
export const DELETE_TODO_FULFILLED = 'DELETE_TODOS_FULFILLED'
export const DELETE_TODO_REJECTED = 'DELETE_TODOS_REJECTED'

//export const apiUrl = "http://localhost:5000/api";